// Mocks generated by Mockito 5.1.0 from annotations
// in clistApp/test/features/clist/data/repositories/get_clist_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:clistApp/core/network/network_info.dart' as _i5;
import 'package:clistApp/features/clist/data/datasources/clist_local.dart'
    as _i2;
import 'package:clistApp/features/clist/data/datasources/clist_remote.dart'
    as _i6;
import 'package:clistApp/features/clist/data/models/clist_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CListLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockCListLocalDataSource extends _i1.Mock
    implements _i2.CListLocalDataSource {
  MockCListLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.CListModel>> getLastCList() => (super.noSuchMethod(
          Invocation.method(#getLastCList, []),
          returnValue: Future<List<_i4.CListModel>>.value(<_i4.CListModel>[]))
      as _i3.Future<List<_i4.CListModel>>);
  @override
  _i3.Future<void> cacheCList(List<_i4.CListModel>? cListModel) =>
      (super.noSuchMethod(Invocation.method(#cacheCList, [cListModel]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i5.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ClistRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockClistRemoteDataSource extends _i1.Mock
    implements _i6.ClistRemoteDataSource {
  @override
  _i3.Future<List<_i4.CListModel>> getCList() => (super.noSuchMethod(
          Invocation.method(#getCList, []),
          returnValue: Future<List<_i4.CListModel>>.value(<_i4.CListModel>[]))
      as _i3.Future<List<_i4.CListModel>>);
}
