// Mocks generated by Mockito 5.1.0 from annotations
// in clistApp/test/features/clist/domain/usecases/get_clist_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:clistApp/core/errors/failures.dart' as _i5;
import 'package:clistApp/features/clist/domain/entities/clist_entity.dart'
    as _i6;
import 'package:clistApp/features/clist/domain/repositories/clist_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetClistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetClistRepository extends _i1.Mock
    implements _i3.GetClistRepository {
  MockGetClistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CList>>> getClist() =>
      (super.noSuchMethod(Invocation.method(#getClist, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.CList>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.CList>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.CList>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CList>>> getCachedClist() =>
      (super.noSuchMethod(Invocation.method(#getCachedClist, []),
          returnValue: Future<_i2.Either<_i5.Failure, List<_i6.CList>>>.value(
              _FakeEither_0<_i5.Failure, List<_i6.CList>>())) as _i4
          .Future<_i2.Either<_i5.Failure, List<_i6.CList>>>);
}
